services:
  mongodb:
    image: 'mongo:latest'
    container_name: "mongodb"
    environment:
      - 'MONGO_INITDB_DATABASE=kitchensink'
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  kitchensink-app:
    build: .
    ports:
      - "8085:8080"
volumes:
  mongodata:
    driver: local
